### ISSUE TITLE
Cursor Text Editing Issue

### ISSUE THREAD

**Issue by liggett2820** [pcdshub/atef#102]
## Expected Behavior
When editing a string of characters, where you click within the string should be where the cursor goes and allows the user to type in that spot.

## Current Behavior
After moving the cursor to the middle of a string, once the user starts typing, the cursor moves to the end of the string and add on from the end.

However, this bug does not affect the text box when filling out a PV name to compare.

## Steps to Reproduce (for bugs)

1. Type in a text box.
2. Click somewhere within the already typed text.
3. Start typing again, and the cursor will skip to the end of the line.

## Context
This prevents quick edits and undoing typos without having to delete unnecessary characters. Implements unnecessary time spent on editing and hinders ease of use.

## Your Environment
source pcds_conda
My repo: /cds/home/l/liggett1/atef

**Comment by ZLLentz** [comment]
It looks like this affects specifically the "expanding line edit" style text boxes- the one-line text entry widgets where the box can get longer as we type longer name. Very annoying bug, thank you for reporting.

**Comment by ZLLentz** [comment]
I've tracked down the source of this bug.

There is a code routine that runs whenever you edit any of these `QLineEdit`-based widgets that takes your new string and copies it into the internal data structure for the file.

There is a second code routine that runs whenever the data structure updates to copy the update over to the input widgets. This is so that if we have multiple text boxes that edit the same data point, like the name, the other text boxes update when you change the name using the first text box.

The two functions that can update a `QLineEdit` both have a side-effect of moving the cursor to the end of the text box on update. So we're creating this annoying little feedback loop where you start typing, the text in the box gets overwritten with the same string again, and your cursor gets thrown to the end.

I'll find a simple fix, probably skipping the update if the text is already correct or if it's in focus, one of the two.
