### ISSUE TITLE
BUG: PV Configs have no scrollbar

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/atef#75]
See title
Gets long really fast

**Comment by klauer** [comment]
(Commenting here instead of the linked PR to keep discussions a bit more focused)

Current proposal is replacing the PV listing with a multiline text edit widget.

I think it would be good for copy/pasting a bunch of entries conveniently, though maybe it would be annoying to have to carefully select a line to remove a single PV - or require the user to care about empty lines and such. I wonder then if a list widget should be considered instead? Copy/pasting multiple items wouldn't be built-in, of course, but it could be added.

**Comment by ZLLentz** [comment]
Would you believe that this is the first I've seen `QListWidget` from the developer side? There are lots of features in qt that I haven't explored. It's definitely worth looking at.

**Comment by ZLLentz** [comment]
It looks like the way to go will be re-using your `StringListWithDialog` widget + pairing it with a multiline edit widget for the data entry

**Comment by klauer** [comment]
Sounds good to me! 👍
