### ISSUE TITLE
BUG: type selection in equality widget seems shaky

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/atef#78]
## Expected Behavior

It should be easy to save our value as the desired type

## Current Behavior

I had some strange issues where my values got saved as "0.0" string type- I can't remember exactly what I was trying to do in these cases. I think I might have been trying to set 0 integers? Needs investigation.

**Comment by liggett2820** [comment]
I have come across something similar. Sometimes when I try to change the data type from the default float to something else like a bool, after saving and closing, the value will stay the same but the data type will change back to bool.

I have found that if you change the value first, then change the data type after, and then save it, the data type will save as the one you changed it to. 

To change it again, the user has to change the data type back to float, change the actual value, the change the data type back again to the desired type in order to save it "properly".

I don't know if this is something to look into or just let the user know the order of steps to take to save a changed data type.

**Comment by ZLLentz** [comment]
I'm in the process of redoing how the types are handled here, which should make this issue go away. I haven't seen this again on my wip branch so here's hoping.
