### ISSUE TITLE
Discussion: NALMS integration and EPICS alarms

### ISSUE THREAD

**Issue by klauer** [pcdshub/atef#83]
## Thoughts on alarms

* Could atef verify that a device has passed NALMS checks - without reduplicating its effort?
* Would NALMS entries have to be structured in a way that tied it back to happi device names?
* Does atef need to be cognizant of alarm states in general? ophyd does not currently allow for easy access to such information, unfortunately

**Comment by klauer** [comment]
@ZLLentz, I feel like this is something we should figure out in conjunction with #123. 

(Or at the very least, we should ensure we're not painted into a corner by ignoring alarms again.)

**Comment by ZLLentz** [comment]
A few disconnected thoughts:

- Perhaps the most straightforward approach would be adding a "NALMS" check alongside equals, etc. that simply looks up our PV/signal in NALMS? (I don't remember the precise architecture).

- But I think you're suggesting something a bit more- that we should be able to find all NALMS entries associated with a device name. Which also is reasonable. I need to remind myself how NALMS entries are organized and how another app could sift through them.

- A big part of NALMS is making the built-in EPICS alarms useful- rather than NALMSing should we just have better built-in support for EPICS alarms?

**Comment by klauer** [comment]
>  A big part of NALMS is making the built-in EPICS alarms useful- rather than NALMSing should we just have better built-in support for EPICS alarms?

I think this is the most concerning one for now. I should have pointed out what was in my head a bit more clearly (rather, at all) above.

We currently do not stash alarm severity anywhere in the caching mechanism, and ophyd doesn't make it easy to access. Non-`EpicsSignal` instances won't even have severities, of course.

(The integration with NALMS is probably important but I don't see it as being such a fundamental, lower-layer thing that needs deciding _now_)

**Comment by klauer** [comment]
(NALMS may have an option to generate summary EPICS PVs but we haven't heard about this possibility from Jesse just yet.)

**Comment by klauer** [comment]
A PyDM data plugin for accessing NALMS state is available here: [slac-alarm-manager](https://github.com/slaclab/slac-alarm-manager). atef could potentially use it directly (pretending it's PyDM) or preferably just use it as a basis for our own implementation here.

**Comment by klauer** [comment]
This is a stale discussion. @tangkong should we close it?

**Comment by tangkong** [comment]
Stale indeed.  Integration may be possible in the future but we should refresh our thoughts on it.  To my knowledge NALMS doesn't broadcast information, it only consumes it
